version: '3.8'

services:
  app:
    container_name: turistdata_app
    image: "${DOCKERIMAGE}"
    environment:
      - PYTHONUNBUFFERED=1
      - HOST_PORT_BACKEND
      - PORT=8000
      - HOST
      - DBURL
      - DBNAME
      - DBUSER
      - DBPASSW
      - CORS_ORIGIN
      - "${HOST_PORT_BACKEND}:8000"
    command: python app.py
